---
title: "Assignment 4: Sample Size and Design"
author: 'Team 1: Milan Filipovic, Vivian Truong, Lillian Chen'
date: "4/29/2021"
output: 
  html_document:
    toc: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# 1. Type I and II Errors, Power, Effect Size 



# 2. Basic formulas for power and sample size 


# 3. Sample size based on coefficient of variation 


# 4. Sample size calculation for the Poisson distribution 


# 5. Sample size calculation for the Binomial distribution 

Mean and proportions are two of the most important parameters in statistics because they arise frequently in life:

+ What proportion of patients benefit from a drug?
+ Is the C-section proportion the same for white women and black women who give birth?
+ What is the probability a person is a carrier of a rare genetic defect? 


We model $Y_i$ as a Binomial random variable with batch size $m_i$ and "success" probability $p_i$
$$
\mathbb{P}(Y_i = y_i) = \binom{m_i}{y_i} p_i^{y_i} (1 - p_i)^{m_i - y_i}.
$$
Where $E(Y_i)=np$ and $Var(Y_i)=np(1-p)$. 

Suppose we want to compare two different proportions $\pi_0$ and $\pi_1$. Recall the basic formula for calculating sample size:
$$
n=\frac{16}{\Delta^2}
$$
Belle proposes the following rule of thumb for calculating binomial sample size:
$$
n=\frac{16\bar{\pi}(1-\bar{\pi})}{(\pi_0-\pi_1)^2}
$$
Where $\bar{\pi}=\frac{(\pi_0+\pi_1)}{2}$ is used as the average variance of the two proportions. 

## Discussion and Extension

This approximation is good for values of n that come out between 10 and 100. More exact formulas should be used to determine sample sizes for values of n outside of this range. 

# 6. Systematic effects due to randomization 

Randomization refers to the act of randomly assigning subjects in a study to different treatment groups.

## Rule (Belle)
**Randomization puts systematic sources of variability into the error term.**

Care must be taken to ensure that there is no pattern or bias in the assignment of subjects and that every subject is as likely as any other to be assigned to a treatment or control group. 

## Basis for Randomization
There are three component to randomization

+ Systematic effects are turned into error. 
+ Unknown factors influencing outcome are balanced with known factors. 
+ Randomization provides the basis for statistical procedures that are used to address areas of scientific interest:
  - Tests of significance
  - Analysis of Variance 
  - Confidence Intervals


# 7. Blocking 
The concept of blocking is to break up the subjects into a number of blocks, and then to randomize the subjects within these blocks. The systematic effects between blocks can be eliminated because we do not care about these sources of variance and want minimize their impact on inference. 

## Examples of blocking
Blocks can be any group that is more homogeneous than the population. Age group or alcohol consumption could be potential blocking variables in a study interested with the effects of smoking for example, because individuals within the same age group or rate of alcohol consumption may be more homogeneous in smoking habits. 

A paired study or matched study design are strong examples of blocking because each subject is paired with an equivalent. This reduces treatment-between-subject variability. Crossover studies are also good examples of blocking because the subject receives both treatments, and so the comparison is within subject. 

## Example - Pot Position in Greenhouse
Researchers were interested in comparing different experimental designs to measure which plant growth trait resulted in the most growth. One confounding variable is position within greenhouse - some plants may be exposed to more sun and therefore undergo more growth. Different experimental designs were tested to determine the best way to reduce variance caused by position. One experimental design was to rotate the pots so that each plant was positioned in different parts of the greenhouse over the study. An alternative design was to block the plants according to the growth trait, and then randomize at each position in the greenhouse (fixed-position design). The rotation scheme is similar to a crossover study, whereas the fixed-position controlled for treatment-between-subject variability. The researchers found that blocking with fixed-position was more efficient than re-arrangement of pots and concluded that re-arrangement should be abandoned in favor of fixed-position design.
[Source](https://plantmethods.biomedcentral.com/articles/10.1186/s13007-019-0527-4)

# 8. Factorial designs 


# 9. Balanced designs 


# 10. Missing data 


# 11. Multiple comparisons 


# 12. Bootstrapping 

